In [1]:
import pandas as pd
import pdf
import web_scrape
import single_pdf as spdf
import ML
import analysis
import sql_export

In [2]:

tot_csv = web_scrape.get_csv(2010, 2026) #modify years later to 2010 and 2026
df = pd.read_csv("data/omega_pdfs.csv")
print(df.head())

Saving results to: /Users/mekaelyesfa/Olympic-Swimming-Data-Project/data/omega_pdfs.csv
Year 2010: Found 13 competitions.
  [SAVED] CONOCO PHILLIPS NATIONAL CHAMPIONSHIPS
  [SAVED] SPEEDO JUNIOR NATIONAL CHAMPIONSHIPS
  [SAVED] MUTUAL OF OMAHA PAN PACIFIC CHAMPIONSHIPS
  [SAVED] FINA/ARENA SWIMMING WORLD CUP
  [SAVED] FINA/ARENA SWIMMING WORLD CUP
  [SAVED] FINA/ARENA SWIMMING WORLD CUP
  [SAVED] FINA/ARENA SWIMMING WORLD CUP
  [SAVED] FINA/ARENA SWIMMING WORLD CUP
  [SAVED] FINA/ARENA SWIMMING WORLD CUP
  [SAVED] USA SWIMMING LONG COURSE INVITATIONAL
Year 2010 summary: 10 races saved

Year 2011: Found 14 competitions.
  [SAVED] CONOCOPHILLIPS NATIONAL CHAMPIONSHIPS
  [SAVED] SPEEDO JUNIOR CHAMPIONSHIPS
  [SAVED] FINA/ARENA SWIMMING WORLD CUP
  [SAVED] FINA/ARENA SWIMMING WORLD CUP
  [SAVED] FINA/ARENA SWIMMING WORLD CUP
  [SAVED] FINA/ARENA SWIMMING WORLD CUP
  [SAVED] FINA/ARENA SWIMMING WORLD CUP
  [SAVED] FINA/ARENA SWIMMING WORLD CUP
  [SAVED] FINA/ARENA SWIMMING WORLD CUP
  [SAVED] DUEL IN THE POOL (USA VS EUROPE)
Year 2011 summary: 10 races saved

Year 2012: Found 17 competitions.
  [SAVED] CANADIAN OLYMPIC SWIMMING TRIALS
  [SAVED] LEN EUROPEAN CHAMPIONSHIPS
  [SAVED] MUTUAL OF OMAHA SWIMVITATIONAL
  [SAVED] U.S. OLYMPIC TEAM TRIALS
  [SAVED] FINA/ARENA SWIMMING WORLD CUP 2012
  [SAVED] FINA/ARENA SWIMMING WORLD CUP 2012
  [SAVED] FINA/ARENA SWIMMING WORLD CUP 2012
  [SAVED] FINA/ARENA SWIMMING WORLD CUP 2012
  [SAVED] FINA/ARENA SWIMMING WORLD CUP 2012
  [SAVED] FINA/ARENA SWIMMING WORLD CUP 2012
  [SAVED] FINA/ARENA SWIMMING WORLD CUP 2012
  [SAVED] FINA/ARENA SWIMMING WORLD CUP 2012
Year 2012 summary: 12 races saved

Year 2013: Found 12 competitions.
  [SAVED] 2013 PHILLIPS 66 NATIONAL CHAMPIONSHIPS & WORLD CHAMPIONSHIP TRIALS
  [SAVED] 2013 U.S. OPEN SWIMMING CHAMPIONSHIPS
  [SAVED] SPEEDO JUNIOR NATIONAL SWIMMING CHAMPIONSHIPS
  [SAVED] FINA SWIMMING WORLD CUP 2013 EINDHOVEN 1/8
  [SAVED] FINA SWIMMING WORLD CUP 2013 BERLIN 2/8
  [SAVED] FINA SWIMMING WORLD CUP 2013 MOSCOW 3/8
  [SAVED] FINA SWIMMING WORLD CUP 2013 DUBAI 4/8
  [SAVED] FINA SWIMMING WORLD CUP 2013 DOHA 5/8
  [SAVED] FINA SWIMMING WORLD CUP 2013 SINGAPORE 6/8
  [SAVED] FINA SWIMMING WORLD CUP 2013 TOKYO 7/8
  [SAVED] FINA SWIMMING WORLD CUP 2013 BEIJING 8/8
Year 2013 summary: 11 races saved

Year 2014: Found 13 competitions.
  [SAVED] 2013-2014 ARENA GRAND PRIX SERIES
  [SAVED] 2013-2014 ARENA GRAND PRIX SERIES
  [SAVED] 2014 SPEEDO JUNIOR NATIONAL CHAMPIONSHIPS
  [SAVED] 2014 PHILLIPS 66 NATIONAL CHAMPIONSHIPS
  [SAVED] FINA/MASTBANK SWIMMING WORLD CUP 2014
  [SAVED] FINA/MASTBANK SWIMMING WORLD CUP 2014
  [SAVED] FINA/MASTBANK SWIMMING WORLD CUP 2014
  [SAVED] FINA/MASTBANK SWIMMING WORLD CUP 2014
  [SAVED] FINA/MASTBANK SWIMMING WORLD CUP 2014
  [SAVED] FINA/MASTBANK SWIMMING WORLD CUP 2014
  [SAVED] FINA/MASTBANK SWIMMING WORLD CUP 2014
Year 2014 summary: 11 races saved

Year 2015: Found 14 competitions.
  [SAVED] ARENA PRO SWIM SERIES AT MESA
  [SAVED] 2015 SPEEDO JUNIOR NATIONAL CHAMPIONSHIPS
  [SAVED] PHILLIPS 66 NATIONAL CHAMPIONSHIPS
  [SAVED] FINA/AIRWEAVE SWIMMING WORLD CUP 2015
  [SAVED] FINA/AIRWEAVE SWIMMING WORLD CUP 2015
  [SAVED] 5TH FINA WORLD JUNIOR SWIMMING CHAMPIONSHIPS 2015
  [SAVED] FINA/AIRWEAVE SWIMMING WORLD CUP 2015
  [SAVED] FINA/AIRWEAVE SWIMMING WORLD CUP 2015
  [SAVED] FINA/AIRWEAVE SWIMMING WORLD CUP 2015
  [SAVED] FINA/AIRWEAVE SWIMMING WORLD CUP 2015
  [SAVED] FINA/AIRWEAVE SWIMMING WORLD CUP 2015
  [SAVED] FINA/AIRWEAVE SWIMMING WORLD CUP 2015
  [SAVED] AT&T WINTER NATIONAL CHAMPIONSHIPS
  [SAVED] MUTUAL OF OMAHA DUEL IN THE POOL
Year 2015 summary: 14 races saved

Year 2016: Found 17 competitions.
  [ERROR] 2016 CANADIAN OLYMPIC AND PARA-SWIMMING TRIALS: Message:
Stacktrace:
0   chromedriver                        0x0000000104ac16b4 cxxbridge1$str$ptr + 3127600
1   chromedriver                        0x0000000104ab9a50 cxxbridge1$str$ptr + 3095756
2   chromedriver                        0x000000010459656c _RNvCsdExgN8vFLbb_7___rustc35___rust_no_alloc_shim_is_unstable_v2 + 75432
3   chromedriver                        0x00000001045df864 _RNvCsdExgN8vFLbb_7___rustc35___rust_no_alloc_shim_is_unstable_v2 + 375200
4   chromedriver                        0x000000010461e620 _RNvCsdExgN8vFLbb_7___rustc35___rust_no_alloc_shim_is_unstable_v2 + 632668
5   chromedriver                        0x00000001045d3b9c _RNvCsdExgN8vFLbb_7___rustc35___rust_no_alloc_shim_is_unstable_v2 + 326872
6   chromedriver                        0x0000000104a80680 cxxbridge1$str$ptr + 2861308
7   chromedriver                        0x0000000104a83dd4 cxxbridge1$str$ptr + 2875472
8   chromedriver                        0x0000000104a65a7c cxxbridge1$str$ptr + 2751736
9   chromedriver                        0x0000000104a84658 cxxbridge1$str$ptr + 2877652
10  chromedriver                        0x0000000104a55ffc cxxbridge1$str$ptr + 2687608
11  chromedriver                        0x0000000104aa8d78 cxxbridge1$str$ptr + 3026932
12  chromedriver                        0x0000000104aa8ef4 cxxbridge1$str$ptr + 3027312
13  chromedriver                        0x0000000104ab96a8 cxxbridge1$str$ptr + 3094820
14  libsystem_pthread.dylib             0x0000000198bdfc08 _pthread_start + 136
15  libsystem_pthread.dylib             0x0000000198bdaba8 thread_start + 8

  [SAVED] 2015-2016 ARENA PRO SWIM SERIES
  [SAVED] 2015-16 ARENA PRO SWIM SERIES
  [SAVED] U.S. OLYMPIC TEAM TRIALS - SWIMMING
  [SAVED] FINA/AIRWEAVE SWIMMING WORLD CUP 2016
  [SAVED] FINA/AIRWEAVE SWIMMING WORLD CUP 2016
  [SAVED] FINA/AIRWEAVE SWIMMING WORLD CUP 2016
  [SAVED] FINA/AIRWEAVE SWIMMING WORLD CUP 2016
  [SAVED] FINA/AIRWEAVE SWIMMING WORLD CUP 2016
  [SAVED] FINA/AIRWEAVE SWIMMING WORLD CUP 2016
  [SAVED] FINA/AIRWEAVE SWIMMING WORLD CUP 2016
  [SAVED] FINA/AIRWEAVE SWIMMING WORLD CUP 2016
  [SAVED] FINA/AIRWEAVE SWIMMING WORLD CUP 2016
Year 2016 summary: 12 races saved

Year 2017: Found 14 competitions.
  [SAVED] 2017 ARENA PRO SWIM SERIES
  [SAVED] 2017 ARENA PRO SWIM SERIES
  [SAVED] 2017 ARENA PRO SWIM SERIES
  [SAVED] 2017 PHILLIPS 66 NATIONAL CHAMPIONSHIIPS AND WORLD CHAMPIONSHIP TRIALS
  [SAVED] FINA/AIRWEAVE SWIMMING WORLD CUP 2017
  [SAVED] FINA/AIRWEAVE SWIMMING WORLD CUP 2017
  [SAVED] FINA/AIRWEAVE SWIMMING WORLD CUP 2017
  [SAVED] 6TH FINA WORLD JUNIOR CHAMPIONSHIPS 2017
  [SAVED] FINA/AIRWEAVE SWIMMING WORLD CUP 2017
  [SAVED] FINA/AIRWEAVE SWIMMING WORLD CUP 2017
  [SAVED] FINA/AIRWEAVE SWIMMING WORLD CUP 2017
  [SAVED] FINA/AIRWEAVE SWIMMING WORLD CUP 2017
  [SAVED] FINA/AIRWEAVE SWIMMING WORLD CUP 2017
Year 2017 summary: 13 races saved

Year 2018: Found 14 competitions.
  [SAVED] 2018 TYR PRO SWIM SERIES
  [SAVED] 2018 TYR PRO SWIM SERIES
  [SAVED] 2018 PHILLIPS 66 NATIONAL CHAMPS
  [SAVED] 2018 SPEEDO JUNIOR NATIONAL CHAMPIONSHIPS
  [SAVED] FINA SWIMMING WORLD CUP 2018
  [SAVED] FINA SWIMMING WORLD CUP 2018
  [SAVED] FINA SWIMMING WORLD CUP 2018
  [SAVED] FINA SWIMMING WORLD CUP 2018
  [SAVED] FINA SWIMMING WORLD CUP 2018
  [SAVED] FINA SWIMMING WORLD CUP 2018
  [SAVED] FINA SWIMMING WORLD CUP 2018
  [SAVED] 2018 WINTER NATIONAL CHAMPIONSHIPS
Year 2018 summary: 12 races saved

Year 2019: Found 16 competitions.
  [SAVED] 2019 TYR PRO SWIM SERIES #3 RICHMOND
  [SAVED] FINA CHAMPIONS SWIM SERIES
  [SAVED] FINA CHAMPIONS SWIM SERIES
  [SAVED] FINA CHAMPIONS SWIM SERIES
  [SAVED] 2019 TYR PRO SWIM SERIES #5 CLOVIS
  [SAVED] 2019 PHILLIPS 66 NATIONAL CHAMPS
  [SAVED] FINA SWIMMING WORLD CUP 2019
  [SAVED] 2019 SPEEDO JUNIOR NATIONAL CHAMPIONSHIPS
  [SAVED] FINA SWIMMING WORLD CUP 2019
  [SAVED] FINA SWIMMING WORLD CUP 2019
  [SAVED] 7TH FINA WORLD JUNIOR SWIMMING CHAMPIONSHIPS 2019
  [SAVED] FINA SWIMMING WORLD CUP 2019
  [SAVED] FINA SWIMMING WORLD CUP 2019
  [SAVED] FINA SWIMMING WORLD CUP 2019
  [SAVED] FINA SWIMMING WORLD CUP 2019
  [SAVED] 2019 TOYOTA U.S. OPEN
Year 2019 summary: 16 races saved

Year 2020: Found 17 competitions.
  [SAVED] FINA CHAMPIONS SWIM SERIES
  [SAVED] 2019-20 -TYR PRO SWIM SERIES #2 KNOXVILLE
  [SAVED] FINA CHAMPIONS SWIM SERIES
  [SAVED] 2020 TOYOTA U.S. OPEN CHAMPIONSHIPS-GREENSBORO
Year 2020 summary: 4 races saved

Year 2021: Found 28 competitions.
  [SAVED] 2021 TYR PRO SWIM SERIES - SAN ANTONIO
  [SAVED] 2021 TYR PRO SWIM SERIES - INDIANAPOLIS
  [SAVED] 2020 U.S. OLYMPIC TEAM TRIALS WAVE I
  [SAVED] 2020 U.S. OLYMPIC TEAM TRIALS WAVE II
  [SAVED] FINA SWIMMING WORLD CUP 2021
  [SAVED] FINA SWIMMING WORLD CUP 2021
  [SAVED] FINA SWIMMING WORLD CUP 2021
  [SAVED] FINA SWIMMING WORLD CUP 2021
  [SAVED] 2021 TOYOTA US OPEN CHAMPIONSHIPS
Year 2021 summary: 9 races saved

Year 2022: Found 9 competitions.
  [SAVED] PHILLIPS 66 INTERNATIONAL TEAM TRIALS
  [SAVED] 2022 PHILLIPS 66 NATIONAL CHAMPIONSHIPS
  [SAVED] 2022 SPEEDO JUNIOR NATIONAL CHAMPIONSHIPS
  [SAVED] 8TH FINA WORLD JUNIOR SWIMMING CHAMPIONSHIPS
  [SAVED] FINA SWIMMING WORLD CUP 2022
  [SAVED] FINA SWIMMING WORLD CUP 2022
  [SAVED] FINA SWIMMING WORLD CUP 2022
  [SAVED] 2022 TOYOTA US OPEN CHAMPIONSHIPS
Year 2022 summary: 8 races saved

Year 2023: Found 9 competitions.
  [SAVED] 2023 TYR PRO SWIM SERIES - FORT LAUDERDALE
  [SAVED] 2023 TYR PRO SERIES - WESTMONT
  [SAVED] 2023 PHILLIPS 66 NATIONAL CHAMPIONSHIPS
  [SAVED] WORLD AQUATICS JUNIOR SWIMMING CHAMPIONSHIPS
  [SAVED] WORLD AQUATICS SWIMMING WORLD CUP
  [SAVED] WORLD AQUATICS SWIMMING WORLD CUP
  [SAVED] WORLD AQUATICS SWIMMING WORLD CUP
  [SAVED] 2023 TOYOTA US OPEN CHAMPIONSHIPS
Year 2023 summary: 8 races saved

Year 2024: Found 9 competitions.
  [SAVED] 2024 TYR PRO SWIM SERIES - WESTMONT
  [SAVED] 2024 TYR PRO SWIM SERIES - SAN ANTONIO
  [SAVED] 2024 US OLYMPIC TEAM TRIALS
  [SAVED] WORLD AQUATICS SWIMMING WORLD CUP
  [SAVED] WORLD AQUATICS SWIMMING WORLD CUP
  [SAVED] WORLD AQUATICS SWIMMING WORLD CUP
Year 2024 summary: 6 races saved

Year 2025: Found 11 competitions.
  [SAVED] 2025 TYR PRO SWIM SERIES
  [SAVED] 2025 TYR PRO SWIM SERIES
  [SAVED] 2025 TYR PRO SWIM SERIES
  [SAVED] 2025 TOYOTA NATIONAL CHAMPIONSHIPS
  [SAVED] WORLD AQUATICS JUNIOR SWIMMING CHAMPIONSHIPS
  [SAVED] WORLD AQUATICS SWIMMING WORLD CUP
  [SAVED] WORLD AQUATICS SWIMMING WORLD CUP
  [SAVED] WORLD AQUATICS SWIMMING WORLD CUP
  [SAVED] 2025 TOYOTA U.S. OPEN CHAMPIONSHIPS
Year 2025 summary: 9 races saved

Error selecting year 2026: Message:

Year 2026: Found 1 competitions.
  [SAVED] 2026 USA SWIMMING PRO SWIM SERIES
Year 2026 summary: 1 races saved

   year                                competition  \
0  2010     CONOCO PHILLIPS NATIONAL CHAMPIONSHIPS
1  2010       SPEEDO JUNIOR NATIONAL CHAMPIONSHIPS
2  2010  MUTUAL OF OMAHA PAN PACIFIC CHAMPIONSHIPS
3  2010              FINA/ARENA SWIMMING WORLD CUP
4  2010              FINA/ARENA SWIMMING WORLD CUP

                                   mens_400_free_pdf  \
0  https://www.omegatiming.com/File/00010A1100090...
1  https://www.omegatiming.com/File/00010A0C00210...
2  https://www.omegatiming.com/File/00010A0B00310...
3  https://www.omegatiming.com/File/00010A09001B0...
4  https://www.omegatiming.com/File/00010A08001C0...

                                 womens_400_free_pdf
0  https://www.omegatiming.com/File/00010A11000C0...
1  https://www.omegatiming.com/File/00010A0C00200...
2  https://www.omegatiming.com/File/00010A0B00300...
3  https://www.omegatiming.com/File/00010A09003B0...
4  https://www.omegatiming.com/File/00010A08003A0...

In [3]:
print("getting links")
men_pdf_links, women_pdf_links = pdf.get_links_df(df)
print("printing links")
#print(men_pdf_links, women_pdf_links)

getting links
printing links

In [6]:
import pandas as pd

links_df = pd.read_csv("data/omega_pdfs.csv")
men_pdf_links, women_pdf_links = pdf.get_links_df(links_df)

print(len(men_pdf_links), len(women_pdf_links))

165 164

In [8]:
print("scraping men")
men_df = pdf.scrape_omega(men_pdf_links, output_file="data/men_df.csv")

print("done")
#men_df = pd.read_csv("men_df.csv")

scraping men

Scraping:   1%|▏                                | 1/165 [00:02<07:58,  2.91s/it]

https://www.omegatiming.com/File/00010A0B0031000000FFFFFFFFFFFF01.pdf rows: 16

Scraping:   1%|▍                                | 2/165 [00:03<04:39,  1.72s/it]

https://www.omegatiming.com/File/00010A09001B000000FFFFFFFFFFFF01.pdf rows: 8
https://www.omegatiming.com/File/00010A110009000000FFFFFFFFFFFF01.pdf rows: 24

Scraping:   2%|▊                                | 4/165 [00:04<02:10,  1.23it/s]

https://www.omegatiming.com/File/00010A08001C000000FFFFFFFFFFFF01.pdf rows: 8

Scraping:   3%|█                                | 5/165 [00:04<01:46,  1.50it/s]

https://www.omegatiming.com/File/00010A0C0021000000FFFFFFFFFFFF01.pdf rows: 24

Scraping:   4%|█▏                               | 6/165 [00:07<03:31,  1.33s/it]

https://www.omegatiming.com/File/00010A07001C000000FFFFFFFFFFFF01.pdf rows: 8
https://www.omegatiming.com/File/00010A04001B000000FFFFFFFFFFFF01.pdf rows: 8

Scraping:   5%|█▌                               | 8/165 [00:07<02:07,  1.23it/s]

https://www.omegatiming.com/File/00010A05001D000000FFFFFFFFFFFF01.pdf rows: 8
https://www.omegatiming.com/File/00010A06001B000000FFFFFFFFFFFF01.pdf rows: 8

Scraping:   6%|█▉                              | 10/165 [00:09<01:52,  1.38it/s]

https://www.omegatiming.com/File/00010A01000B000000FFFFFFFFFFFF01.pdf rows: 11

Scraping:   7%|██▏                             | 11/165 [00:09<01:54,  1.34it/s]

https://www.omegatiming.com/File/00010B0B0023000000FFFFFFFFFFFF01.pdf rows: 30

Scraping:   7%|██▎                             | 12/165 [00:10<01:43,  1.47it/s]

https://www.omegatiming.com/File/00010B090019000000FFFFFFFFFFFF01.pdf rows: 8

Scraping:   8%|██▌                             | 13/165 [00:11<01:49,  1.39it/s]

https://www.omegatiming.com/File/00010B0C0008000000FFFFFFFFFFFF01.pdf rows: 30

Scraping:   8%|██▋                             | 14/165 [00:12<02:12,  1.14it/s]

https://www.omegatiming.com/File/00010B08001D000000FFFFFFFFFFFF01.pdf rows: 8

Scraping:   9%|██▉                             | 15/165 [00:12<01:48,  1.38it/s]

https://www.omegatiming.com/File/00010B06001C000000FFFFFFFFFFFF01.pdf rows: 8

Scraping:  10%|███                             | 16/165 [00:13<01:38,  1.51it/s]

https://www.omegatiming.com/File/00010B07001C000000FFFFFFFFFFFF01.pdf rows: 8

Scraping:  10%|███▎                            | 17/165 [00:14<02:03,  1.20it/s]

https://www.omegatiming.com/File/00010B05001B000000FFFFFFFFFFFF01.pdf rows: 8

Scraping:  11%|███▍                            | 18/165 [00:15<02:21,  1.04it/s]

https://www.omegatiming.com/File/00010B04001B000000FFFFFFFFFFFF01.pdf rows: 8
https://www.omegatiming.com/File/00010B03001E000000FFFFFFFFFFFF01.pdf rows: 8

Scraping:  12%|███▉                            | 20/165 [00:16<01:31,  1.59it/s]

https://www.omegatiming.com/File/00010B00000D000000FFFFFFFFFFFF01.pdf rows: 8

Scraping:  13%|████                            | 21/165 [00:17<01:48,  1.33it/s]

https://www.omegatiming.com/File/00010C010100000302FFFFFFFFFFFF02.pdf rows: 24

Scraping:  13%|████▎                           | 22/165 [00:18<01:48,  1.32it/s]

https://www.omegatiming.com/File/00010C01002D000000FFFFFFFFFFFF01.pdf rows: 18

Scraping:  14%|████▍                           | 23/165 [00:18<01:40,  1.42it/s]

https://www.omegatiming.com/File/00010C010200000302FFFFFFFFFFFF02.pdf rows: 8

Scraping:  15%|████▋                           | 24/165 [00:19<01:22,  1.72it/s]

https://www.omegatiming.com/File/00010C030000000001FFFFFFFFFFFF01.pdf rows: 8

Scraping:  15%|████▊                           | 25/165 [00:19<01:28,  1.58it/s]

https://www.omegatiming.com/File/00010C010400000302FFFFFFFFFFFF02.pdf rows: 8

Scraping:  16%|█████                           | 26/165 [00:21<01:57,  1.19it/s]

https://www.omegatiming.com/File/00010C010600000302FFFFFFFFFFFF02.pdf rows: 8
https://www.omegatiming.com/File/00010C010700000302FFFFFFFFFFFF02.pdf rows: 8

Scraping:  17%|█████▍                          | 28/165 [00:22<01:30,  1.52it/s]

https://www.omegatiming.com/File/00010C010300000302FFFFFFFFFFFF02.pdf rows: 8

Scraping:  18%|█████▊                          | 30/165 [00:22<01:04,  2.08it/s]

https://www.omegatiming.com/File/00010C010500000302FFFFFFFFFFFF02.pdf rows: 8
https://www.omegatiming.com/File/00010C010900000302FFFFFFFFFFFF02.pdf rows: 8

Scraping:  19%|██████                          | 31/165 [00:23<01:26,  1.55it/s]

https://www.omegatiming.com/File/00010C010800000302FFFFFFFFFFFF02.pdf rows: 8

Scraping:  19%|██████▏                         | 32/165 [00:25<01:54,  1.16it/s]

https://www.omegatiming.com/File/00010D020000000302FFFFFFFFFFFF02.pdf rows: 23

Scraping:  20%|██████▍                         | 33/165 [00:25<01:34,  1.40it/s]

https://www.omegatiming.com/File/00010C010A00000302FFFFFFFFFFFF02.pdf rows: 8

Scraping:  21%|██████▌                         | 34/165 [00:26<01:35,  1.37it/s]

https://www.omegatiming.com/File/00010D020300000302FFFFFFFFFFFF02.pdf rows: 24

Scraping:  22%|██████▉                         | 36/165 [00:26<00:58,  2.21it/s]

https://www.omegatiming.com/File/00010D020500000302FFFFFFFFFFFF02.pdf rows: 8
https://www.omegatiming.com/File/00010D020200000302FFFFFFFFFFFF02.pdf rows: 24

Scraping:  22%|███████▏                        | 37/165 [00:28<01:32,  1.38it/s]

https://www.omegatiming.com/File/00010D020600000300FFFFFFFFFFFF02.pdf rows: 21
https://www.omegatiming.com/File/00010D020900000302FFFFFFFFFFFF02.pdf rows: 8

Scraping:  24%|███████▌                        | 39/165 [00:28<01:16,  1.65it/s]

https://www.omegatiming.com/File/00010D020800000302FFFFFFFFFFFF02.pdf rows: 8

Scraping:  24%|███████▊                        | 40/165 [00:29<01:22,  1.51it/s]

https://www.omegatiming.com/File/00010D020700000302FFFFFFFFFFFF02.pdf rows: 8

Scraping:  25%|████████▏                       | 42/165 [00:31<01:14,  1.66it/s]

https://www.omegatiming.com/File/00010D020B00000302FFFFFFFFFFFF02.pdf rows: 8
https://www.omegatiming.com/File/00010D020A00000302FFFFFFFFFFFF02.pdf rows: 8

Scraping:  26%|████████▎                       | 43/165 [00:31<01:07,  1.81it/s]

https://www.omegatiming.com/File/00010D020C00000300FFFFFFFFFFFF02.pdf rows: 23
https://www.omegatiming.com/File/00010E010000000302FFFFFFFFFFFF02.pdf rows: 32

Scraping:  27%|████████▋                       | 45/165 [00:33<01:31,  1.32it/s]

https://www.omegatiming.com/File/00010E010200000302FFFFFFFFFFFF02.pdf rows: 24
https://www.omegatiming.com/File/00010E010100000302FFFFFFFFFFFF02.pdf rows: 36

Scraping:  28%|█████████                       | 47/165 [00:33<01:06,  1.77it/s]

https://www.omegatiming.com/File/00010E010300000302FFFFFFFFFFFF02.pdf rows: 24

Scraping:  29%|█████████▎                      | 48/165 [00:34<01:04,  1.81it/s]

https://www.omegatiming.com/File/00010E010500000300FFFFFFFFFFFF02.pdf rows: 15

Scraping:  30%|█████████▌                      | 49/165 [00:35<01:05,  1.76it/s]

https://www.omegatiming.com/File/00010E010700000302FFFFFFFFFFFF02.pdf rows: 8

Scraping:  30%|█████████▋                      | 50/165 [00:35<01:13,  1.56it/s]

https://www.omegatiming.com/File/00010E010600000300FFFFFFFFFFFF02.pdf rows: 22

Scraping:  31%|█████████▉                      | 51/165 [00:36<01:11,  1.59it/s]

https://www.omegatiming.com/File/00010E010900000302FFFFFFFFFFFF02.pdf rows: 8

Scraping:  32%|██████████                      | 52/165 [00:37<01:27,  1.29it/s]

https://www.omegatiming.com/File/00010E010B00000302FFFFFFFFFFFF02.pdf rows: 8

Scraping:  32%|██████████▎                     | 53/165 [00:38<01:22,  1.35it/s]

https://www.omegatiming.com/File/00010E010A00000302FFFFFFFFFFFF02.pdf rows: 7

Scraping:  33%|██████████▍                     | 54/165 [00:39<01:36,  1.14it/s]

https://www.omegatiming.com/File/00010E010C00000302FFFFFFFFFFFF02.pdf rows: 8

Scraping:  33%|██████████▋                     | 55/165 [00:40<01:24,  1.30it/s]

https://www.omegatiming.com/File/00010F020900000302FFFFFFFFFFFF02.pdf rows: 32

Scraping:  35%|███████████                     | 57/165 [00:41<01:09,  1.55it/s]

https://www.omegatiming.com/File/00010F020100000302FFFFFFFFFFFF02.pdf rows: 8
https://www.omegatiming.com/File/00010F020A00000302FFFFFFFFFFFF02.pdf rows: 24

Scraping:  35%|███████████▏                    | 58/165 [00:41<01:08,  1.55it/s]

https://www.omegatiming.com/File/00010F020B00000302FFFFFFFFFFFF02.pdf rows: 24

Scraping:  36%|███████████▍                    | 59/165 [00:42<01:09,  1.52it/s]

https://www.omegatiming.com/File/00010F020200000302FFFFFFFFFFFF02.pdf rows: 8

Scraping:  36%|███████████▋                    | 60/165 [00:43<01:20,  1.30it/s]

https://www.omegatiming.com/File/00010F020E00000302FFFFFFFFFFFF02.pdf rows: 8

Scraping:  37%|███████████▊                    | 61/165 [00:44<01:30,  1.14it/s]

https://www.omegatiming.com/File/00010F020300000302FFFFFFFFFFFF02.pdf rows: 8

Scraping:  38%|████████████                    | 62/165 [00:45<01:11,  1.44it/s]

https://www.omegatiming.com/File/00010F020500000300FFFFFFFFFFFF02.pdf rows: 10

Scraping:  38%|████████████▏                   | 63/165 [00:45<01:12,  1.42it/s]

https://www.omegatiming.com/File/00010F020400000302FFFFFFFFFFFF02.pdf rows: 8

Scraping:  39%|████████████▍                   | 64/165 [00:46<01:05,  1.53it/s]

https://www.omegatiming.com/File/00010F020600000302FFFFFFFFFFFF02.pdf rows: 8

Scraping:  39%|████████████▌                   | 65/165 [00:47<01:12,  1.39it/s]

https://www.omegatiming.com/File/00010F020700000302FFFFFFFFFFFF02.pdf rows: 8

Scraping:  40%|████████████▊                   | 66/165 [00:48<01:21,  1.21it/s]

https://www.omegatiming.com/File/00010F020C00000302FFFFFFFFFFFF02.pdf rows: 24

Scraping:  41%|████████████▉                   | 67/165 [00:48<01:06,  1.48it/s]

https://www.omegatiming.com/File/00010F020800000302FFFFFFFFFFFF02.pdf rows: 8

Scraping:  42%|█████████████▍                  | 69/165 [00:49<00:55,  1.73it/s]

https://www.omegatiming.com/File/00010F020D00000302FFFFFFFFFFFF02.pdf rows: 6
https://www.omegatiming.com/File/000110000200000302FFFFFFFFFFFF02.pdf rows: 32

Scraping:  42%|█████████████▌                  | 70/165 [00:49<00:45,  2.08it/s]

https://www.omegatiming.com/File/000110000300000302FFFFFFFFFFFF02.pdf rows: 8

Scraping:  43%|█████████████▊                  | 71/165 [00:50<00:57,  1.64it/s]

https://www.omegatiming.com/File/000110000100000302FFFFFFFFFFFF02.pdf rows: 32

Scraping:  44%|█████████████▉                  | 72/165 [00:51<00:48,  1.90it/s]

https://www.omegatiming.com/File/000110000500000302FFFFFFFFFFFF02.pdf rows: 7

Scraping:  44%|██████████████▏                 | 73/165 [00:52<00:59,  1.54it/s]

https://www.omegatiming.com/File/000110000400000302FFFFFFFFFFFF02.pdf rows: 7

Scraping:  45%|██████████████▎                 | 74/165 [00:52<00:48,  1.89it/s]

https://www.omegatiming.com/File/000110000600000302FFFFFFFFFFFF02.pdf rows: 8

Scraping:  45%|██████████████▌                 | 75/165 [00:52<00:40,  2.20it/s]

https://www.omegatiming.com/File/000110000800000302FFFFFFFFFFFF02.pdf rows: 8

Scraping:  46%|██████████████▋                 | 76/165 [00:53<00:46,  1.91it/s]

https://www.omegatiming.com/File/000110000700000302FFFFFFFFFFFF02.pdf rows: 8

Scraping:  47%|██████████████▉                 | 77/165 [00:55<01:23,  1.05it/s]

https://www.omegatiming.com/File/000110000B00000302FFFFFFFFFFFF02.pdf rows: 8

Scraping:  47%|███████████████▏                | 78/165 [00:56<01:22,  1.06it/s]

https://www.omegatiming.com/File/000110000C00000302FFFFFFFFFFFF02.pdf rows: 8

Scraping:  48%|███████████████▌                | 80/165 [00:56<00:49,  1.72it/s]

https://www.omegatiming.com/File/000110000900000302FFFFFFFFFFFF02.pdf rows: 8
https://www.omegatiming.com/File/000110000A00000302FFFFFFFFFFFF02.pdf rows: 8

Scraping:  49%|███████████████▋                | 81/165 [00:57<01:00,  1.38it/s]

https://www.omegatiming.com/File/000111010C00000302FFFFFFFFFFFF02.pdf rows: 32
https://www.omegatiming.com/File/000111010B00000302FFFFFFFFFFFF02.pdf rows: 32

Scraping:  50%|████████████████                | 83/165 [00:58<00:37,  2.16it/s]

https://www.omegatiming.com/File/000111010D00000302FFFFFFFFFFFF02.pdf rows: 32

Scraping:  51%|████████████████▎               | 84/165 [00:59<00:55,  1.45it/s]

https://www.omegatiming.com/File/00011101030101EF04FFFFFFFFFFFF01.pdf rows: 8

Scraping:  52%|████████████████▍               | 85/165 [01:00<00:56,  1.41it/s]

https://www.omegatiming.com/File/000111010E00000302FFFFFFFFFFFF02.pdf rows: 24

Scraping:  52%|████████████████▋               | 86/165 [01:00<00:51,  1.52it/s]

https://www.omegatiming.com/File/000111010000000302FFFFFFFFFFFF02.pdf rows: 8

Scraping:  53%|████████████████▊               | 87/165 [01:01<00:47,  1.65it/s]

https://www.omegatiming.com/File/00011101010101EF04FFFFFFFFFFFF01.pdf rows: 8

Scraping:  53%|█████████████████               | 88/165 [01:02<00:56,  1.37it/s]

https://www.omegatiming.com/File/00011101070101EF04FFFFFFFFFFFF01.pdf rows: 8

Scraping:  54%|█████████████████▎              | 89/165 [01:02<00:49,  1.54it/s]

https://www.omegatiming.com/File/00011101040101EF04FFFFFFFFFFFF01.pdf rows: 8

Scraping:  55%|█████████████████▍              | 90/165 [01:03<00:43,  1.73it/s]

https://www.omegatiming.com/File/00011101060101EF04FFFFFFFFFFFF01.pdf rows: 8

Scraping:  55%|█████████████████▋              | 91/165 [01:03<00:46,  1.58it/s]

https://www.omegatiming.com/File/00011101090101EF04FFFFFFFFFFFF01.pdf rows: 8
https://www.omegatiming.com/File/00011101080101EF01FFFFFFFFFFFF01.pdf rows: 21

Scraping:  56%|██████████████████              | 93/165 [01:05<00:50,  1.42it/s]

https://www.omegatiming.com/File/00011201020101EF04FFFFFFFFFFFF01.pdf rows: 32

Scraping:  57%|██████████████████▏             | 94/165 [01:06<00:53,  1.34it/s]

https://www.omegatiming.com/File/000112010000000302FFFFFFFFFFFF02.pdf rows: 32
https://www.omegatiming.com/File/00011201030101EF04FFFFFFFFFFFF01.pdf rows: 24

Scraping:  58%|██████████████████▌             | 96/165 [01:06<00:34,  2.00it/s]

https://www.omegatiming.com/File/000112010100000302FFFFFFFFFFFF02.pdf rows: 32

Scraping:  59%|██████████████████▊             | 97/165 [01:09<01:04,  1.06it/s]

https://www.omegatiming.com/File/00011201080101EF04FFFFFFFFFFFF01.pdf rows: 8
https://www.omegatiming.com/File/00011201050101EF04FFFFFFFFFFFF01.pdf rows: 8

Scraping:  60%|███████████████████▏            | 99/165 [01:09<00:48,  1.36it/s]

https://www.omegatiming.com/File/00011201070101EF04FFFFFFFFFFFF01.pdf rows: 8
https://www.omegatiming.com/File/00011201060101EF04FFFFFFFFFFFF01.pdf rows: 8

Scraping:  61%|██████████████████▉            | 101/165 [01:12<01:02,  1.03it/s]

https://www.omegatiming.com/File/000112010A0101EF04FFFFFFFFFFFF01.pdf rows: 8
https://www.omegatiming.com/File/000112010B0101EF04FFFFFFFFFFFF01.pdf rows: 8
https://www.omegatiming.com/File/00011201090101EF04FFFFFFFFFFFF01.pdf rows: 8

Scraping:  63%|███████████████████▌           | 104/165 [01:13<00:41,  1.48it/s]

https://www.omegatiming.com/File/00011201040101EF04FFFFFFFFFFFF01.pdf rows: 24

Scraping:  65%|████████████████████           | 107/165 [01:15<00:36,  1.57it/s]

https://www.omegatiming.com/File/000113010E0101EF04FFFFFFFFFFFF01.pdf rows: 4
https://www.omegatiming.com/File/000113010F0101EF04FFFFFFFFFFFF01.pdf rows: 4
https://www.omegatiming.com/File/00011301080101EF04FFFFFFFFFFFF01.pdf rows: 32

Scraping:  65%|████████████████████▎          | 108/165 [01:17<00:44,  1.29it/s]

https://www.omegatiming.com/File/00011301090101EF04FFFFFFFFFFFF01.pdf rows: 4

Scraping:  66%|████████████████████▍          | 109/165 [01:19<00:58,  1.04s/it]

https://www.omegatiming.com/File/000113010A0101EF04FFFFFFFFFFFF01.pdf rows: 19
https://www.omegatiming.com/File/000113010B0101EF04FFFFFFFFFFFF01.pdf rows: 32

Scraping:  67%|████████████████████▊          | 111/165 [01:19<00:41,  1.29it/s]

https://www.omegatiming.com/File/000113010C0101EF04FFFFFFFFFFFF01.pdf rows: 24

Scraping:  68%|█████████████████████          | 112/165 [01:20<00:40,  1.30it/s]

https://www.omegatiming.com/File/00011301000101EF04FFFFFFFFFFFF01.pdf rows: 8

Scraping:  68%|█████████████████████▏         | 113/165 [01:21<00:41,  1.25it/s]

https://www.omegatiming.com/File/00011301100101EF04FFFFFFFFFFFF01.pdf rows: 8

Scraping:  69%|█████████████████████▍         | 114/165 [01:21<00:34,  1.49it/s]

https://www.omegatiming.com/File/00011301010101EF04FFFFFFFFFFFF01.pdf rows: 8

Scraping:  70%|█████████████████████▌         | 115/165 [01:22<00:30,  1.61it/s]

https://www.omegatiming.com/File/00011301040101EF04FFFFFFFFFFFF01.pdf rows: 8

Scraping:  72%|██████████████████████▏        | 118/165 [01:24<00:26,  1.76it/s]

https://www.omegatiming.com/File/00011301030101EF04FFFFFFFFFFFF01.pdf rows: 8
https://www.omegatiming.com/File/00011301020101EF04FFFFFFFFFFFF01.pdf rows: 8
https://www.omegatiming.com/File/00011301050101EF04FFFFFFFFFFFF01.pdf rows: 8

Scraping:  72%|██████████████████████▎        | 119/165 [01:24<00:27,  1.66it/s]

https://www.omegatiming.com/File/00011301060101EF04FFFFFFFFFFFF01.pdf rows: 8

Scraping:  73%|██████████████████████▌        | 120/165 [01:25<00:31,  1.44it/s]

https://www.omegatiming.com/File/00011402020101EF04FFFFFFFFFFFF01.pdf rows: 32

Scraping:  74%|██████████████████████▉        | 122/165 [01:26<00:21,  1.98it/s]

https://www.omegatiming.com/File/00011402000101EF04FFFFFFFFFFFF01.pdf rows: 4
https://www.omegatiming.com/File/000113010D0101EF04FFFFFFFFFFFF01.pdf rows: 32

Scraping:  75%|███████████████████████▎       | 124/165 [01:28<00:26,  1.53it/s]

https://www.omegatiming.com/File/00011402010101EF04FFFFFFFFFFFF01.pdf rows: 4
https://www.omegatiming.com/File/00011402100101EF04FFFFFFFFFFFF01.pdf rows: 14

Scraping:  76%|███████████████████████▍       | 125/165 [01:29<00:24,  1.61it/s]

https://www.omegatiming.com/File/00011500010101EF04FFFFFFFFFFFF01.pdf rows: 16

Scraping:  76%|███████████████████████▋       | 126/165 [01:29<00:25,  1.52it/s]

https://www.omegatiming.com/File/00011500000101EF04FFFFFFFFFFFF01.pdf rows: 10

Scraping:  77%|███████████████████████▊       | 127/165 [01:31<00:32,  1.16it/s]

https://www.omegatiming.com/File/00011500030101EF04FFFFFFFFFFFF01.pdf rows: 8

Scraping:  78%|████████████████████████       | 128/165 [01:31<00:31,  1.16it/s]

https://www.omegatiming.com/File/00011500020101EF04FFFFFFFFFFFF01.pdf rows: 16

Scraping:  78%|████████████████████████▏      | 129/165 [01:32<00:27,  1.29it/s]

https://www.omegatiming.com/File/000115000F0101EF04FFFFFFFFFFFF01.pdf rows: 8
https://www.omegatiming.com/File/00011500110101EF04FFFFFFFFFFFF01.pdf rows: 8

Scraping:  79%|████████████████████████▌      | 131/165 [01:33<00:23,  1.48it/s]

https://www.omegatiming.com/File/00011500100101EF04FFFFFFFFFFFF01.pdf rows: 8

Scraping:  80%|████████████████████████▊      | 132/165 [01:34<00:23,  1.38it/s]

https://www.omegatiming.com/File/00011500120101EF04FFFFFFFFFFFF01.pdf rows: 8

Scraping:  81%|████████████████████████▉      | 133/165 [01:36<00:30,  1.04it/s]

https://www.omegatiming.com/File/00011700020101EF0104FFFFFFFFFF01.pdf rows: 24
https://www.omegatiming.com/File/00011700010101EF0104FFFFFFFFFF01.pdf rows: 24
https://www.omegatiming.com/File/000115001C0101EF04FFFFFFFFFFFF01.pdf rows: 22

Scraping:  84%|█████████████████████████▉     | 138/165 [01:37<00:13,  1.98it/s]

https://www.omegatiming.com/File/00011700070101EF0104FFFFFFFFFF01.pdf rows: 8
https://www.omegatiming.com/File/00011700080101EF0104FFFFFFFFFF01.pdf rows: 8
https://www.omegatiming.com/File/00011700040101EF0104FFFFFFFFFF01.pdf rows: 28

Scraping:  84%|██████████████████████████     | 139/165 [01:39<00:17,  1.46it/s]

https://www.omegatiming.com/File/00011700060101EF0104FFFFFFFFFF01.pdf rows: 24
https://www.omegatiming.com/File/00011600000101EF0104FFFFFFFFFF01.pdf rows: 24

Scraping:  86%|██████████████████████████▋    | 142/165 [01:40<00:11,  1.99it/s]

https://www.omegatiming.com/File/00011700050101EF0104FFFFFFFFFF01.pdf rows: 8
https://www.omegatiming.com/File/00011700090101EF0104FFFFFFFFFF01.pdf rows: 8

Scraping:  87%|██████████████████████████▊    | 143/165 [01:40<00:11,  1.87it/s]

https://www.omegatiming.com/File/00011600020101EF0104FFFFFFFFFF01.pdf rows: 24
https://www.omegatiming.com/File/00011600030101EF0104FFFFFFFFFF01.pdf rows: 32

Scraping:  88%|███████████████████████████▍   | 146/165 [01:43<00:12,  1.48it/s]

https://www.omegatiming.com/File/00011600070101EF0104FFFFFFFFFF01.pdf rows: 8
https://www.omegatiming.com/File/00011600080101EF0104FFFFFFFFFF01.pdf rows: 8

Scraping:  89%|███████████████████████████▌   | 147/165 [01:44<00:13,  1.38it/s]

https://www.omegatiming.com/File/00011600060101EF0104FFFFFFFFFF01.pdf rows: 8

Scraping:  90%|███████████████████████████▊   | 148/165 [01:45<00:11,  1.45it/s]

https://www.omegatiming.com/File/00011600050101EF0104FFFFFFFFFF01.pdf rows: 8
https://www.omegatiming.com/File/00011600040101EF0104FFFFFFFFFF01.pdf rows: 24

Scraping:  91%|████████████████████████████▏  | 150/165 [01:46<00:09,  1.59it/s]

https://www.omegatiming.com/File/00011800020101EF0104FFFFFFFFFF01.pdf rows: 24

Scraping:  92%|████████████████████████████▎  | 151/165 [01:46<00:08,  1.62it/s]

https://www.omegatiming.com/File/00011800050101EF0104FFFFFFFFFF01.pdf rows: 8

Scraping:  92%|████████████████████████████▌  | 152/165 [01:47<00:07,  1.76it/s]

https://www.omegatiming.com/File/00011800010101EF0104FFFFFFFFFF01.pdf rows: 24

Scraping:  93%|████████████████████████████▋  | 153/165 [01:47<00:06,  1.85it/s]

https://www.omegatiming.com/File/00011800030101EF0104FFFFFFFFFF01.pdf rows: 8

Scraping:  93%|████████████████████████████▉  | 154/165 [01:49<00:09,  1.20it/s]

https://www.omegatiming.com/File/00011900020101EF0104FFFFFFFFFF01.pdf rows: 16

Scraping:  95%|█████████████████████████████▍ | 157/165 [01:49<00:03,  2.21it/s]

https://www.omegatiming.com/File/00011800070101EF0104FFFFFFFFFF01.pdf rows: 8
https://www.omegatiming.com/File/00011900000101EF0104FFFFFFFFFF01.pdf rows: 24
https://www.omegatiming.com/File/00011800060101EF0104FFFFFFFFFF01.pdf rows: 8

Scraping:  96%|█████████████████████████████▋ | 158/165 [01:51<00:05,  1.24it/s]

https://www.omegatiming.com/File/00011900060101EF0104FFFFFFFFFF01.pdf rows: 48

Scraping:  97%|██████████████████████████████ | 160/165 [01:52<00:02,  1.76it/s]

https://www.omegatiming.com/File/00011900050101EF0104FFFFFFFFFF01.pdf rows: 8
https://www.omegatiming.com/File/00011900040101EF0104FFFFFFFFFF01.pdf rows: 31

Scraping:  98%|██████████████████████████████▏| 161/165 [01:52<00:02,  1.89it/s]

https://www.omegatiming.com/File/00011900030101EF0104FFFFFFFFFF01.pdf rows: 24

Scraping:  98%|██████████████████████████████▍| 162/165 [01:54<00:02,  1.18it/s]

https://www.omegatiming.com/File/00011A00000101EF0104FFFFFFFFFF01.pdf rows: 23

Scraping:  99%|██████████████████████████████▌| 163/165 [01:55<00:01,  1.29it/s]

https://www.omegatiming.com/File/00011900080101EF0104FFFFFFFFFF01.pdf rows: 31

Scraping:  99%|██████████████████████████████▊| 164/165 [01:55<00:00,  1.40it/s]

https://www.omegatiming.com/File/00011900070101EF0104FFFFFFFFFF01.pdf rows: 33

Scraping: 100%|███████████████████████████████| 165/165 [01:56<00:00,  1.42it/s]

https://www.omegatiming.com/File/00011900090101EF0104FFFFFFFFFF01.pdf rows: 24
done

In [9]:

print("scraping women")
women_df = pdf.scrape_omega(women_pdf_links, output_file="data/women_df.csv")
print("done")
#women_df = pd.read_csv("men_df.csv")

scraping women

Scraping:   1%|▏                                | 1/164 [00:02<06:20,  2.33s/it]

https://www.omegatiming.com/File/00010A0B0030000000FFFFFFFFFFFF01.pdf rows: 16

Scraping:   2%|▌                                | 3/164 [00:03<02:23,  1.12it/s]

https://www.omegatiming.com/File/00010A09003B000000FFFFFFFFFFFF01.pdf rows: 8
https://www.omegatiming.com/File/00010A0C0020000000FFFFFFFFFFFF01.pdf rows: 24

Scraping:   2%|▊                                | 4/164 [00:03<01:55,  1.39it/s]

https://www.omegatiming.com/File/00010A11000C000000FFFFFFFFFFFF01.pdf rows: 24

Scraping:   3%|█                                | 5/164 [00:04<02:13,  1.19it/s]

https://www.omegatiming.com/File/00010A07003D000000FFFFFFFFFFFF01.pdf rows: 8
https://www.omegatiming.com/File/00010A08003A000000FFFFFFFFFFFF01.pdf rows: 8
https://www.omegatiming.com/File/00010A06003D000000FFFFFFFFFFFF01.pdf rows: 8

Scraping:   5%|█▊                               | 9/164 [00:06<01:22,  1.88it/s]

https://www.omegatiming.com/File/00010A05003F000000FFFFFFFFFFFF01.pdf rows: 8
https://www.omegatiming.com/File/00010B0C000B000000FFFFFFFFFFFF01.pdf rows: 30

Scraping:   6%|█▉                              | 10/164 [00:07<01:34,  1.63it/s]

https://www.omegatiming.com/File/00010A04003C000000FFFFFFFFFFFF01.pdf rows: 8

Scraping:   7%|██▎                             | 12/164 [00:08<01:15,  2.03it/s]

https://www.omegatiming.com/File/00010B090034000000FFFFFFFFFFFF01.pdf rows: 5
https://www.omegatiming.com/File/00010A01000A000000FFFFFFFFFFFF01.pdf rows: 9

Scraping:   8%|██▌                             | 13/164 [00:09<01:24,  1.79it/s]

https://www.omegatiming.com/File/00010B08003F000000FFFFFFFFFFFF01.pdf rows: 8

Scraping:   9%|██▋                             | 14/164 [00:10<01:45,  1.42it/s]

https://www.omegatiming.com/File/00010B0B0022000000FFFFFFFFFFFF01.pdf rows: 30

Scraping:   9%|██▉                             | 15/164 [00:10<01:39,  1.49it/s]

https://www.omegatiming.com/File/00010B070040000000FFFFFFFFFFFF01.pdf rows: 8

Scraping:  10%|███                             | 16/164 [00:11<01:45,  1.40it/s]

https://www.omegatiming.com/File/00010B05003C000000FFFFFFFFFFFF01.pdf rows: 8

Scraping:  10%|███▎                            | 17/164 [00:11<01:26,  1.69it/s]

https://www.omegatiming.com/File/00010B06003F000000FFFFFFFFFFFF01.pdf rows: 8

Scraping:  11%|███▌                            | 18/164 [00:12<01:11,  2.05it/s]

https://www.omegatiming.com/File/00010B030041000000FFFFFFFFFFFF01.pdf rows: 8

Scraping:  12%|███▋                            | 19/164 [00:13<01:30,  1.60it/s]

https://www.omegatiming.com/File/00010B00000C000000FFFFFFFFFFFF01.pdf rows: 7

Scraping:  12%|███▉                            | 20/164 [00:13<01:29,  1.60it/s]

https://www.omegatiming.com/File/00010B04003D000000FFFFFFFFFFFF01.pdf rows: 8

Scraping:  13%|████                            | 21/164 [00:14<01:40,  1.42it/s]

https://www.omegatiming.com/File/00010C030001010101FFFFFFFFFFFF01.pdf rows: 8

Scraping:  14%|████▍                           | 23/164 [00:15<01:20,  1.76it/s]

https://www.omegatiming.com/File/00010C010031000000FFFFFFFFFFFF01.pdf rows: 17
https://www.omegatiming.com/File/00010C010101001702FFFFFFFFFFFF02.pdf rows: 24

Scraping:  15%|████▋                           | 24/164 [00:16<01:33,  1.50it/s]

https://www.omegatiming.com/File/00010C010301001702FFFFFFFFFFFF02.pdf rows: 8

Scraping:  15%|████▉                           | 25/164 [00:17<01:31,  1.52it/s]

https://www.omegatiming.com/File/00010C010501001702FFFFFFFFFFFF02.pdf rows: 8
https://www.omegatiming.com/File/00010C010201001702FFFFFFFFFFFF02.pdf rows: 8

Scraping:  16%|█████▎                          | 27/164 [00:17<01:13,  1.86it/s]

https://www.omegatiming.com/File/00010C010401001702FFFFFFFFFFFF02.pdf rows: 8
https://www.omegatiming.com/File/00010C010601001702FFFFFFFFFFFF02.pdf rows: 8

Scraping:  18%|█████▋                          | 29/164 [00:18<01:02,  2.18it/s]

https://www.omegatiming.com/File/00010C010801001702FFFFFFFFFFFF02.pdf rows: 8

Scraping:  18%|█████▊                          | 30/164 [00:19<01:16,  1.75it/s]

https://www.omegatiming.com/File/00010C010701001700FFFFFFFFFFFF02.pdf rows: 25

Scraping:  19%|██████                          | 31/164 [00:20<01:24,  1.58it/s]

https://www.omegatiming.com/File/00010C010A01001702FFFFFFFFFFFF02.pdf rows: 8
https://www.omegatiming.com/File/00010C010901001702FFFFFFFFFFFF02.pdf rows: 8

Scraping:  20%|██████▍                         | 33/164 [00:21<01:07,  1.94it/s]

https://www.omegatiming.com/File/00010D020201001702FFFFFFFFFFFF02.pdf rows: 24

Scraping:  21%|██████▋                         | 34/164 [00:21<01:12,  1.80it/s]

https://www.omegatiming.com/File/00010D020501001702FFFFFFFFFFFF02.pdf rows: 8

Scraping:  22%|███████                         | 36/164 [00:22<00:58,  2.18it/s]

https://www.omegatiming.com/File/00010D020001001702FFFFFFFFFFFF02.pdf rows: 24
https://www.omegatiming.com/File/00010D020601001700FFFFFFFFFFFF02.pdf rows: 18

Scraping:  23%|███████▏                        | 37/164 [00:23<01:10,  1.81it/s]

https://www.omegatiming.com/File/00010D020701001702FFFFFFFFFFFF02.pdf rows: 8

Scraping:  23%|███████▍                        | 38/164 [00:23<01:08,  1.85it/s]

https://www.omegatiming.com/File/00010D020801001702FFFFFFFFFFFF02.pdf rows: 8
https://www.omegatiming.com/File/00010D020301001702FFFFFFFFFFFF02.pdf rows: 24

Scraping:  24%|███████▊                        | 40/164 [00:25<01:20,  1.55it/s]

https://www.omegatiming.com/File/00010D020C01001702FFFFFFFFFFFF02.pdf rows: 8
https://www.omegatiming.com/File/00010D020B01001702FFFFFFFFFFFF02.pdf rows: 8

Scraping:  26%|████████▏                       | 42/164 [00:25<01:03,  1.92it/s]

https://www.omegatiming.com/File/00010D020901001702FFFFFFFFFFFF02.pdf rows: 8

Scraping:  26%|████████▍                       | 43/164 [00:26<01:08,  1.78it/s]

https://www.omegatiming.com/File/00010D020A01001702FFFFFFFFFFFF02.pdf rows: 8

Scraping:  27%|████████▌                       | 44/164 [00:27<01:15,  1.58it/s]

https://www.omegatiming.com/File/00010E010201001702FFFFFFFFFFFF02.pdf rows: 24

Scraping:  27%|████████▊                       | 45/164 [00:27<01:05,  1.82it/s]

https://www.omegatiming.com/File/00010E010101001702FFFFFFFFFFFF02.pdf rows: 36

Scraping:  28%|████████▉                       | 46/164 [00:28<01:01,  1.91it/s]

https://www.omegatiming.com/File/00010E010301001702FFFFFFFFFFFF02.pdf rows: 24

Scraping:  29%|█████████▏                      | 47/164 [00:28<01:03,  1.85it/s]

https://www.omegatiming.com/File/00010E010001001702FFFFFFFFFFFF02.pdf rows: 32

Scraping:  29%|█████████▎                      | 48/164 [00:30<01:24,  1.37it/s]

https://www.omegatiming.com/File/00010E010501001702FFFFFFFFFFFF02.pdf rows: 7

Scraping:  30%|█████████▌                      | 49/164 [00:30<01:23,  1.37it/s]

https://www.omegatiming.com/File/00010E010701001702FFFFFFFFFFFF02.pdf rows: 8

Scraping:  30%|█████████▊                      | 50/164 [00:31<01:14,  1.53it/s]

https://www.omegatiming.com/File/00010E010901001702FFFFFFFFFFFF02.pdf rows: 8
https://www.omegatiming.com/File/00010E010601001700FFFFFFFFFFFF02.pdf rows: 15

Scraping:  32%|██████████▏                     | 52/164 [00:32<01:07,  1.65it/s]

https://www.omegatiming.com/File/00010E010B01001702FFFFFFFFFFFF02.pdf rows: 8
https://www.omegatiming.com/File/00010E010A01001700FFFFFFFFFFFF02.pdf rows: 21

Scraping:  33%|██████████▌                     | 54/164 [00:32<00:46,  2.38it/s]

https://www.omegatiming.com/File/00010E010C01001702FFFFFFFFFFFF02.pdf rows: 8

Scraping:  34%|██████████▋                     | 55/164 [00:33<01:03,  1.71it/s]

https://www.omegatiming.com/File/00010F020A01001702FFFFFFFFFFFF02.pdf rows: 24
https://www.omegatiming.com/File/00010F020901001702FFFFFFFFFFFF02.pdf rows: 32

Scraping:  35%|███████████                     | 57/164 [00:34<00:46,  2.28it/s]

https://www.omegatiming.com/File/00010F020101001702FFFFFFFFFFFF02.pdf rows: 8

Scraping:  35%|███████████▎                    | 58/164 [00:35<01:02,  1.70it/s]

https://www.omegatiming.com/File/00010F020E01001702FFFFFFFFFFFF02.pdf rows: 8

Scraping:  36%|███████████▌                    | 59/164 [00:35<01:02,  1.67it/s]

https://www.omegatiming.com/File/00010F020B01001702FFFFFFFFFFFF02.pdf rows: 24

Scraping:  37%|███████████▋                    | 60/164 [00:37<01:24,  1.22it/s]

https://www.omegatiming.com/File/00010F020201001702FFFFFFFFFFFF02.pdf rows: 7

Scraping:  37%|███████████▉                    | 61/164 [00:37<01:08,  1.51it/s]

https://www.omegatiming.com/File/00010F020301001702FFFFFFFFFFFF02.pdf rows: 8
https://www.omegatiming.com/File/00010F020401001702FFFFFFFFFFFF02.pdf rows: 8

Scraping:  38%|████████████▎                   | 63/164 [00:39<01:19,  1.26it/s]

https://www.omegatiming.com/File/00010F020501001702FFFFFFFFFFFF02.pdf rows: 15

Scraping:  39%|████████████▍                   | 64/164 [00:40<01:16,  1.31it/s]

https://www.omegatiming.com/File/00010F020801001702FFFFFFFFFFFF02.pdf rows: 8
https://www.omegatiming.com/File/00010F020701001702FFFFFFFFFFFF02.pdf rows: 8

Scraping:  40%|████████████▉                   | 66/164 [00:40<00:57,  1.71it/s]

https://www.omegatiming.com/File/00010F020601001702FFFFFFFFFFFF02.pdf rows: 8

Scraping:  41%|█████████████                   | 67/164 [00:42<01:11,  1.36it/s]

https://www.omegatiming.com/File/00010F020C01001702FFFFFFFFFFFF02.pdf rows: 23

Scraping:  41%|█████████████▎                  | 68/164 [00:43<01:13,  1.31it/s]

https://www.omegatiming.com/File/000110000101001702FFFFFFFFFFFF02.pdf rows: 32

Scraping:  42%|█████████████▍                  | 69/164 [00:43<01:03,  1.50it/s]

https://www.omegatiming.com/File/000110000201001702FFFFFFFFFFFF02.pdf rows: 32

Scraping:  43%|█████████████▋                  | 70/164 [00:43<00:56,  1.66it/s]

https://www.omegatiming.com/File/00010F020D01001702FFFFFFFFFFFF02.pdf rows: 6

Scraping:  43%|█████████████▊                  | 71/164 [00:44<00:59,  1.58it/s]

https://www.omegatiming.com/File/000110000301001702FFFFFFFFFFFF02.pdf rows: 8

Scraping:  44%|██████████████                  | 72/164 [00:44<00:52,  1.75it/s]

https://www.omegatiming.com/File/000110000501001702FFFFFFFFFFFF02.pdf rows: 8

Scraping:  45%|██████████████▏                 | 73/164 [00:45<00:47,  1.92it/s]

https://www.omegatiming.com/File/000110000601001702FFFFFFFFFFFF02.pdf rows: 8

Scraping:  45%|██████████████▍                 | 74/164 [00:46<01:07,  1.33it/s]

https://www.omegatiming.com/File/000110000401001702FFFFFFFFFFFF02.pdf rows: 8
https://www.omegatiming.com/File/000110000801001702FFFFFFFFFFFF02.pdf rows: 8

Scraping:  46%|██████████████▊                 | 76/164 [00:47<00:42,  2.07it/s]

https://www.omegatiming.com/File/000110000701001702FFFFFFFFFFFF02.pdf rows: 8

Scraping:  47%|███████████████                 | 77/164 [00:47<00:52,  1.65it/s]

https://www.omegatiming.com/File/000110000901001702FFFFFFFFFFFF02.pdf rows: 9

Scraping:  48%|███████████████▏                | 78/164 [00:49<01:11,  1.20it/s]

https://www.omegatiming.com/File/000110000C01001702FFFFFFFFFFFF02.pdf rows: 8

Scraping:  48%|███████████████▍                | 79/164 [00:50<01:07,  1.26it/s]

https://www.omegatiming.com/File/000110000A01001702FFFFFFFFFFFF02.pdf rows: 8
https://www.omegatiming.com/File/000110000B01001702FFFFFFFFFFFF02.pdf rows: 8

Scraping:  49%|███████████████▊                | 81/164 [00:50<00:46,  1.79it/s]

https://www.omegatiming.com/File/000111010B01001702FFFFFFFFFFFF02.pdf rows: 32

Scraping:  50%|████████████████                | 82/164 [00:51<00:44,  1.83it/s]

https://www.omegatiming.com/File/000111010C01001702FFFFFFFFFFFF02.pdf rows: 31

Scraping:  51%|████████████████▏               | 83/164 [00:51<00:44,  1.84it/s]

https://www.omegatiming.com/File/000111010E01001702FFFFFFFFFFFF02.pdf rows: 24

Scraping:  51%|████████████████▍               | 84/164 [00:52<00:40,  1.98it/s]

https://www.omegatiming.com/File/00011101010201EF04FFFFFFFFFFFF01.pdf rows: 8

Scraping:  52%|████████████████▌               | 85/164 [00:52<00:40,  1.95it/s]

https://www.omegatiming.com/File/00011101020201EF04FFFFFFFFFFFF01.pdf rows: 8
https://www.omegatiming.com/File/000111010D01001702FFFFFFFFFFFF02.pdf rows: 32

Scraping:  53%|████████████████▉               | 87/164 [00:54<00:47,  1.61it/s]

https://www.omegatiming.com/File/00011101040201EF04FFFFFFFFFFFF01.pdf rows: 7

Scraping:  54%|█████████████████▏              | 88/164 [00:54<00:46,  1.65it/s]

https://www.omegatiming.com/File/00011101060201EF04FFFFFFFFFFFF01.pdf rows: 8

Scraping:  54%|█████████████████▎              | 89/164 [00:55<00:43,  1.72it/s]

https://www.omegatiming.com/File/000111010001001702FFFFFFFFFFFF02.pdf rows: 8
https://www.omegatiming.com/File/00011101070201EF04FFFFFFFFFFFF01.pdf rows: 8

Scraping:  55%|█████████████████▊              | 91/164 [00:56<00:42,  1.73it/s]

https://www.omegatiming.com/File/000112010001001702FFFFFFFFFFFF02.pdf rows: 30

Scraping:  57%|██████████████████▏             | 93/164 [00:57<00:41,  1.73it/s]

https://www.omegatiming.com/File/00011101080201EF04FFFFFFFFFFFF01.pdf rows: 8
https://www.omegatiming.com/File/000112010101001702FFFFFFFFFFFF02.pdf rows: 32

Scraping:  57%|██████████████████▎             | 94/164 [00:57<00:32,  2.18it/s]

https://www.omegatiming.com/File/00011201030201EF04FFFFFFFFFFFF01.pdf rows: 24
https://www.omegatiming.com/File/00011201020201EF04FFFFFFFFFFFF01.pdf rows: 32

Scraping:  59%|██████████████████▋             | 96/164 [00:59<00:38,  1.79it/s]

https://www.omegatiming.com/File/00011201050201EF04FFFFFFFFFFFF01.pdf rows: 8

Scraping:  59%|██████████████████▉             | 97/164 [01:00<00:44,  1.49it/s]

https://www.omegatiming.com/File/00011201060201EF04FFFFFFFFFFFF01.pdf rows: 8

Scraping:  60%|███████████████████             | 98/164 [01:01<00:52,  1.25it/s]

https://www.omegatiming.com/File/00011201070201EF04FFFFFFFFFFFF01.pdf rows: 8
https://www.omegatiming.com/File/00011201080201EF04FFFFFFFFFFFF01.pdf rows: 8

Scraping:  61%|██████████████████▉            | 100/164 [01:01<00:35,  1.80it/s]

https://www.omegatiming.com/File/000112010A0201EF04FFFFFFFFFFFF01.pdf rows: 8

Scraping:  62%|███████████████████            | 101/164 [01:02<00:41,  1.53it/s]

https://www.omegatiming.com/File/00011201090201EF04FFFFFFFFFFFF01.pdf rows: 8

Scraping:  62%|███████████████████▎           | 102/164 [01:04<00:54,  1.13it/s]

https://www.omegatiming.com/File/00011301080201EF04FFFFFFFFFFFF01.pdf rows: 26

Scraping:  63%|███████████████████▍           | 103/164 [01:04<00:48,  1.27it/s]

https://www.omegatiming.com/File/00011201040201EF04FFFFFFFFFFFF01.pdf rows: 24
https://www.omegatiming.com/File/000112010B0201EF04FFFFFFFFFFFF01.pdf rows: 8

Scraping:  64%|███████████████████▊           | 105/164 [01:06<00:42,  1.40it/s]

https://www.omegatiming.com/File/000113010F0201EF04FFFFFFFFFFFF01.pdf rows: 4

Scraping:  65%|████████████████████           | 106/164 [01:06<00:35,  1.65it/s]

https://www.omegatiming.com/File/000113010A0201EF04FFFFFFFFFFFF01.pdf rows: 14
https://www.omegatiming.com/File/000113010E0201EF04FFFFFFFFFFFF01.pdf rows: 4

Scraping:  66%|████████████████████▍          | 108/164 [01:08<00:42,  1.32it/s]

https://www.omegatiming.com/File/00011301090201EF04FFFFFFFFFFFF01.pdf rows: 4

Scraping:  66%|████████████████████▌          | 109/164 [01:08<00:39,  1.41it/s]

https://www.omegatiming.com/File/00011301000201EF04FFFFFFFFFFFF01.pdf rows: 8

Scraping:  67%|████████████████████▊          | 110/164 [01:09<00:39,  1.37it/s]

https://www.omegatiming.com/File/000113010B0201EF04FFFFFFFFFFFF01.pdf rows: 32

Scraping:  68%|████████████████████▉          | 111/164 [01:10<00:33,  1.58it/s]

https://www.omegatiming.com/File/000113010C0201EF04FFFFFFFFFFFF01.pdf rows: 24

Scraping:  68%|█████████████████████▏         | 112/164 [01:12<00:52,  1.01s/it]

https://www.omegatiming.com/File/00011301010201EF04FFFFFFFFFFFF01.pdf rows: 8

Scraping:  69%|█████████████████████▎         | 113/164 [01:12<00:41,  1.24it/s]

https://www.omegatiming.com/File/00011301020201EF04FFFFFFFFFFFF01.pdf rows: 8

Scraping:  70%|█████████████████████▌         | 114/164 [01:12<00:31,  1.57it/s]

https://www.omegatiming.com/File/00011301040201EF04FFFFFFFFFFFF01.pdf rows: 8

Scraping:  70%|█████████████████████▋         | 115/164 [01:13<00:30,  1.61it/s]

https://www.omegatiming.com/File/00011301100201EF04FFFFFFFFFFFF01.pdf rows: 8

Scraping:  71%|█████████████████████▉         | 116/164 [01:14<00:44,  1.08it/s]

https://www.omegatiming.com/File/000113010D0201EF04FFFFFFFFFFFF01.pdf rows: 31

Scraping:  71%|██████████████████████         | 117/164 [01:15<00:36,  1.30it/s]

https://www.omegatiming.com/File/00011301060201EF04FFFFFFFFFFFF01.pdf rows: 9

Scraping:  72%|██████████████████████▎        | 118/164 [01:15<00:29,  1.55it/s]

https://www.omegatiming.com/File/00011301030201EF04FFFFFFFFFFFF01.pdf rows: 8

Scraping:  73%|██████████████████████▋        | 120/164 [01:16<00:20,  2.12it/s]

https://www.omegatiming.com/File/00011301050201EF04FFFFFFFFFFFF01.pdf rows: 8
https://www.omegatiming.com/File/00011402000201EF04FFFFFFFFFFFF01.pdf rows: 4

Scraping:  74%|██████████████████████▊        | 121/164 [01:17<00:25,  1.66it/s]

https://www.omegatiming.com/File/00011402010201EF04FFFFFFFFFFFF01.pdf rows: 4

Scraping:  74%|███████████████████████        | 122/164 [01:17<00:26,  1.61it/s]

https://www.omegatiming.com/File/00011402020201EF04FFFFFFFFFFFF01.pdf rows: 32

Scraping:  75%|███████████████████████▎       | 123/164 [01:18<00:26,  1.54it/s]

https://www.omegatiming.com/File/00011402100201EF04FFFFFFFFFFFF01.pdf rows: 9

Scraping:  76%|███████████████████████▍       | 124/164 [01:19<00:32,  1.24it/s]

https://www.omegatiming.com/File/00011500000201EF04FFFFFFFFFFFF01.pdf rows: 13
https://www.omegatiming.com/File/00011500010201EF04FFFFFFFFFFFF01.pdf rows: 16

Scraping:  77%|███████████████████████▊       | 126/164 [01:20<00:19,  1.91it/s]

https://www.omegatiming.com/File/00011500030201EF04FFFFFFFFFFFF01.pdf rows: 8

Scraping:  77%|████████████████████████       | 127/164 [01:20<00:18,  2.01it/s]

https://www.omegatiming.com/File/00011500020201EF04FFFFFFFFFFFF01.pdf rows: 16

Scraping:  78%|████████████████████████▏      | 128/164 [01:21<00:23,  1.52it/s]

https://www.omegatiming.com/File/00011500110201EF04FFFFFFFFFFFF01.pdf rows: 6

Scraping:  79%|████████████████████████▍      | 129/164 [01:23<00:30,  1.13it/s]

https://www.omegatiming.com/File/00011500120201EF04FFFFFFFFFFFF01.pdf rows: 8

Scraping:  79%|████████████████████████▌      | 130/164 [01:23<00:23,  1.44it/s]

https://www.omegatiming.com/File/000115000F0201EF04FFFFFFFFFFFF01.pdf rows: 8
https://www.omegatiming.com/File/00011500100201EF04FFFFFFFFFFFF01.pdf rows: 8

Scraping:  80%|████████████████████████▉      | 132/164 [01:24<00:22,  1.40it/s]

https://www.omegatiming.com/File/00011700010201EF0104FFFFFFFFFF01.pdf rows: 23

Scraping:  81%|█████████████████████████▏     | 133/164 [01:25<00:18,  1.64it/s]

https://www.omegatiming.com/File/000115001C0201EF04FFFFFFFFFFFF01.pdf rows: 23

Scraping:  82%|█████████████████████████▎     | 134/164 [01:26<00:27,  1.11it/s]

https://www.omegatiming.com/File/00011700020201EF0104FFFFFFFFFF01.pdf rows: 24
https://www.omegatiming.com/File/00011700070201EF0104FFFFFFFFFF01.pdf rows: 8
https://www.omegatiming.com/File/00011700040201EF0104FFFFFFFFFF01.pdf rows: 28

Scraping:  84%|█████████████████████████▉     | 137/164 [01:27<00:14,  1.93it/s]

https://www.omegatiming.com/File/00011700050201EF0104FFFFFFFFFF01.pdf rows: 8

Scraping:  84%|██████████████████████████     | 138/164 [01:28<00:16,  1.57it/s]

https://www.omegatiming.com/File/00011700080201EF0104FFFFFFFFFF01.pdf rows: 8
https://www.omegatiming.com/File/00011700060201EF0104FFFFFFFFFF01.pdf rows: 24

Scraping:  85%|██████████████████████████▍    | 140/164 [01:28<00:11,  2.04it/s]

https://www.omegatiming.com/File/00011600000201EF0104FFFFFFFFFF01.pdf rows: 24

Scraping:  86%|██████████████████████████▋    | 141/164 [01:30<00:14,  1.62it/s]

https://www.omegatiming.com/File/00011600020201EF0104FFFFFFFFFF01.pdf rows: 24
https://www.omegatiming.com/File/00011600030201EF0104FFFFFFFFFF01.pdf rows: 32

Scraping:  87%|███████████████████████████    | 143/164 [01:30<00:09,  2.33it/s]

https://www.omegatiming.com/File/00011700090201EF0104FFFFFFFFFF01.pdf rows: 8

Scraping:  88%|███████████████████████████▏   | 144/164 [01:31<00:12,  1.61it/s]

https://www.omegatiming.com/File/00011600080201EF0104FFFFFFFFFF01.pdf rows: 8

Scraping:  89%|███████████████████████████▌   | 146/164 [01:32<00:10,  1.75it/s]

https://www.omegatiming.com/File/00011600050201EF0104FFFFFFFFFF01.pdf rows: 8
https://www.omegatiming.com/File/00011600070201EF0104FFFFFFFFFF01.pdf rows: 8

Scraping:  90%|███████████████████████████▊   | 147/164 [01:33<00:11,  1.47it/s]

https://www.omegatiming.com/File/00011600060201EF0104FFFFFFFFFF01.pdf rows: 8

Scraping:  91%|████████████████████████████▎  | 150/164 [01:34<00:05,  2.59it/s]

https://www.omegatiming.com/File/00011800010201EF0104FFFFFFFFFF01.pdf rows: 18
https://www.omegatiming.com/File/00011600040201EF0104FFFFFFFFFF01.pdf rows: 24
https://www.omegatiming.com/File/00011800020201EF0104FFFFFFFFFF01.pdf rows: 24

Scraping:  92%|████████████████████████████▌  | 151/164 [01:36<00:09,  1.31it/s]

https://www.omegatiming.com/File/00011800030201EF0104FFFFFFFFFF01.pdf rows: 8

Scraping:  93%|████████████████████████████▋  | 152/164 [01:36<00:08,  1.43it/s]

https://www.omegatiming.com/File/00011800070201EF0104FFFFFFFFFF01.pdf rows: 8

Scraping:  93%|████████████████████████████▉  | 153/164 [01:37<00:08,  1.28it/s]

https://www.omegatiming.com/File/00011800050201EF0104FFFFFFFFFF01.pdf rows: 8
https://www.omegatiming.com/File/00011800060201EF0104FFFFFFFFFF01.pdf rows: 8

Scraping:  95%|█████████████████████████████▎ | 155/164 [01:38<00:05,  1.74it/s]

https://www.omegatiming.com/File/00011900020201EF0104FFFFFFFFFF01.pdf rows: 18

Scraping:  95%|█████████████████████████████▍ | 156/164 [01:39<00:05,  1.44it/s]

https://www.omegatiming.com/File/00011900030201EF0104FFFFFFFFFF01.pdf rows: 24

Scraping:  96%|█████████████████████████████▊ | 158/164 [01:40<00:03,  1.78it/s]

https://www.omegatiming.com/File/00011900000201EF0104FFFFFFFFFF01.pdf rows: 19
https://www.omegatiming.com/File/00011900040201EF0104FFFFFFFFFF01.pdf rows: 31

Scraping:  98%|██████████████████████████████▏| 160/164 [01:42<00:02,  1.61it/s]

https://www.omegatiming.com/File/00011900070201EF0104FFFFFFFFFF01.pdf rows: 21
https://www.omegatiming.com/File/00011900050201EF0104FFFFFFFFFF01.pdf rows: 8

Scraping:  98%|██████████████████████████████▍| 161/164 [01:42<00:01,  2.04it/s]

https://www.omegatiming.com/File/00011900080201EF0104FFFFFFFFFF01.pdf rows: 30

Scraping:  99%|██████████████████████████████▌| 162/164 [01:43<00:01,  1.51it/s]

https://www.omegatiming.com/File/00011900060201EF0104FFFFFFFFFF01.pdf rows: 21

Scraping: 100%|███████████████████████████████| 164/164 [01:43<00:00,  1.58it/s]

https://www.omegatiming.com/File/00011900090201EF0104FFFFFFFFFF01.pdf rows: 24
https://www.omegatiming.com/File/00011A00000201EF0104FFFFFFFFFF01.pdf rows: 20
done

In [12]:
print(men_df.shape)
print(women_df.shape)
print(men_df["Link"].nunique(), "men races parsed")
print(women_df["Link"].nunique(), "women races parsed")
print(men_df["final_time"].min(), men_df["final_time"].max())
print(women_df["final_time"].min(), women_df["final_time"].max())
women_df.sort_values("final_time", ascending=False)[["first_name","last_name","final_time","Link"]].head(10)

(2430, 15)
(2336, 15)
165 men races parsed
164 women races parsed
3:34.46 5:39.58
3:51.87 8:40.99

,first_name,last_name,final_time,Link
265,S7SB6SM7 Emily,SAYEAU,8:40.99,https://www.omegatiming.com/File/00010C0100310...
264,S7SB7SM7 Siobhan SWA 1.13,COUTURE,8:31.92,https://www.omegatiming.com/File/00010C0100310...
263,S6SB5SM6 C.,BERRINGER,7:06.21,https://www.omegatiming.com/File/00010C0100310...
262,S7SB6SM7 Nydia DUCKS 1.34,LANGILL,6:50.78,https://www.omegatiming.com/File/00010C0100310...
261,S6SB6SM6 Danielle,KISSER,6:46.91,https://www.omegatiming.com/File/00010C0100310...
260,S7SB6SM7 S.,MCDOUGALL,6:44.43,https://www.omegatiming.com/File/00010C0100310...
256,S7SB7SM7 Brianna,NELSON,5:43.36,https://www.omegatiming.com/File/00010C0100310...
255,BÉRUBÉ S8SB7SM8 Camille,BÉRUBÉ S8SB7SM8 Camille,5:42.72,https://www.omegatiming.com/File/00010C0100310...
678,8 OKAWA O'CONNELL Kaguya 2000,8 OKAWA O'CONNELL Kaguya 2000,5:41.58,https://www.omegatiming.com/File/00010E0106010...
254,S8SB7SM8 Sarah,MAILHOT,5:39.36,https://www.omegatiming.com/File/00010C0100310...

In [17]:
men_df = men_df[~men_df["first_name"].str.contains(r"S\d|SB|SM", regex=True, na=False)]
women_df = women_df[~women_df["first_name"].str.contains(r"S\d|SB|SM", regex=True, na=False)]
men_df.to_csv("data/men_df.csv", index=False)
women_df.to_csv("data/women_df.csv", index=False)
#print(men_df["final_time"].min(), men_df["final_time"].max())
#print(women_df["final_time"].min(), women_df["final_time"].max())

In [27]:
"""import pandas as pd

# Load data
men = pd.read_csv("data/men_df.csv")
women = pd.read_csv("data/women_df.csv")
links = pd.read_csv("data/omega_pdfs.csv")

# Mark short course competitions
short_mask = links["competition"].str.contains(
    "WORLD CUP|SHORT COURSE|25M",
    case=False,
    na=False
)

# Collect short course PDF links
bad_men_links = set(links.loc[short_mask, "mens_400_free_pdf"].dropna())
bad_women_links = set(links.loc[short_mask, "womens_400_free_pdf"].dropna())

# Filter them out of parsed datasets
men_clean = men[~men["Link"].isin(bad_men_links)].copy()
women_clean = women[~women["Link"].isin(bad_women_links)].copy()

# Save cleaned datasets
men_clean.to_csv("data/men_df.csv", index=False)
women_clean.to_csv("data/women_df.csv", index=False)

# Print summary
print("Original men rows:", len(men))
print("Clean men rows:", len(men_clean))
print("Original women rows:", len(women))
print("Clean women rows:", len(women_clean))
print("Men short-course PDFs removed:", len(bad_men_links))
print("Women short-course PDFs removed:", len(bad_women_links))"""
print(links.loc[short_mask, ["year", "competition"]].drop_duplicates())

     year                                 competition
3    2010               FINA/ARENA SWIMMING WORLD CUP
12   2011               FINA/ARENA SWIMMING WORLD CUP
24   2012          FINA/ARENA SWIMMING WORLD CUP 2012
35   2013  FINA SWIMMING WORLD CUP 2013 EINDHOVEN 1/8
36   2013     FINA SWIMMING WORLD CUP 2013 BERLIN 2/8
37   2013     FINA SWIMMING WORLD CUP 2013 MOSCOW 3/8
38   2013      FINA SWIMMING WORLD CUP 2013 DUBAI 4/8
39   2013       FINA SWIMMING WORLD CUP 2013 DOHA 5/8
40   2013  FINA SWIMMING WORLD CUP 2013 SINGAPORE 6/8
41   2013      FINA SWIMMING WORLD CUP 2013 TOKYO 7/8
42   2013    FINA SWIMMING WORLD CUP 2013 BEIJING 8/8
47   2014       FINA/MASTBANK SWIMMING WORLD CUP 2014
57   2015       FINA/AIRWEAVE SWIMMING WORLD CUP 2015
71   2016       FINA/AIRWEAVE SWIMMING WORLD CUP 2016
84   2017       FINA/AIRWEAVE SWIMMING WORLD CUP 2017
97   2018                FINA SWIMMING WORLD CUP 2018
111  2019                FINA SWIMMING WORLD CUP 2019
129  2021                FINA SWIMMING WORLD CUP 2021
138  2022                FINA SWIMMING WORLD CUP 2022
146  2023           WORLD AQUATICS SWIMMING WORLD CUP
153  2024           WORLD AQUATICS SWIMMING WORLD CUP
161  2025           WORLD AQUATICS SWIMMING WORLD CUP

In [28]:
import pandas as pd
import numpy as np

men = pd.read_csv("data/men_df.csv")
women = pd.read_csv("data/women_df.csv")

men["sex"] = "Men"
women["sex"] = "Women"

df = pd.concat([men, women], ignore_index=True)

print(df.shape)
df.head()

(3074, 16)

,Link,heat,rank,lane,last_name,first_name,reaction_time,split_50m,split_100m,split_150m,split_200m,split_250m,split_300m,split_350m,final_time,sex
0,https://www.omegatiming.com/File/00010A0B00310...,Final A,1,4,PARK,Tae Hwan,0.68,26.33,55.02,1:24.53,1:53.81,2:22.52,2:50.78,3:18.19,3:44.73,Men
1,https://www.omegatiming.com/File/00010A0B00310...,Final A,2,2,COCHRANE,Ryan,0.92,26.63,55.34,1:24.30,1:53.13,2:21.86,2:50.76,3:19.48,3:46.78,Men
2,https://www.omegatiming.com/File/00010A0B00310...,Final A,3,5,ZHANG,Lin,0.74,26.41,55.09,1:24.49,1:53.89,2:22.71,2:51.31,3:18.98,3:46.91,Men
3,https://www.omegatiming.com/File/00010A0B00310...,Final A,4,6,VANDERKAAY,Peter,0.77,26.48,55.40,1:24.46,1:53.89,2:22.79,2:51.45,3:19.67,3:47.11,Men
4,https://www.omegatiming.com/File/00010A0B00310...,Final A,5,3,HOUCHIN,Charlie,0.71,26.67,55.73,1:25.21,1:54.24,2:22.85,2:51.81,3:20.12,3:47.98,Men

In [30]:
import pandas as pd
import numpy as np

men = pd.read_csv("data/men_df.csv")
women = pd.read_csv("data/women_df.csv")

men["sex"] = "Men"
women["sex"] = "Women"

df = pd.concat([men, women], ignore_index=True)

# function to convert mm:ss.xx to seconds
def time_to_seconds(t):
    if pd.isna(t):
        return np.nan
    t = str(t)
    if ":" in t:
        m, s = t.split(":")
        return float(m) * 60 + float(s)
    return float(t)

cols = [
    "reaction_time","split_50m","split_100m","split_150m",
    "split_200m","split_250m","split_300m","split_350m","final_time"
]

for c in cols:
    df[c] = df[c].apply(time_to_seconds)

print("Rows:", len(df))
df.head()

Rows: 3074

,Link,heat,rank,lane,last_name,first_name,reaction_time,split_50m,split_100m,split_150m,split_200m,split_250m,split_300m,split_350m,final_time,sex
0,https://www.omegatiming.com/File/00010A0B00310...,Final A,1,4,PARK,Tae Hwan,0.68,26.33,55.02,84.53,113.81,142.52,170.78,198.19,224.73,Men
1,https://www.omegatiming.com/File/00010A0B00310...,Final A,2,2,COCHRANE,Ryan,0.92,26.63,55.34,84.30,113.13,141.86,170.76,199.48,226.78,Men
2,https://www.omegatiming.com/File/00010A0B00310...,Final A,3,5,ZHANG,Lin,0.74,26.41,55.09,84.49,113.89,142.71,171.31,198.98,226.91,Men
3,https://www.omegatiming.com/File/00010A0B00310...,Final A,4,6,VANDERKAAY,Peter,0.77,26.48,55.40,84.46,113.89,142.79,171.45,199.67,227.11,Men
4,https://www.omegatiming.com/File/00010A0B00310...,Final A,5,3,HOUCHIN,Charlie,0.71,26.67,55.73,85.21,114.24,142.85,171.81,200.12,227.98,Men

In [46]:
import pandas as pd
import importlib
import sql_export

importlib.reload(sql_export)

men = pd.read_csv("data/men_df.csv")
women = pd.read_csv("data/women_df.csv")

sql_df = sql_export.prepare_for_sql(men, women)

sql_export.export_to_sqlite(sql_df)
sql_export.create_indexes()

print("SQL database rows:", sql_export.count_rows())

results = sql_export.run_sample_queries()

print("\nDataset Summary")
print("Men rows:", len(men))
print("Women rows:", len(women))
print("Total rows:", len(men) + len(women))
print("Men races:", men["Link"].nunique())
print("Women races:", women["Link"].nunique())
print("Total races:", men["Link"].nunique() + women["Link"].nunique())

SQL database rows: 3074

--- Top 10 fastest men's swims ---
  first_name    last_name  final_time
0      James          GUY      217.78
1      Conor        DWYER      218.10
2     Connor       JAEGER      218.36
3       Zane       GROTHE      219.70
4    Michael        KLUEH      220.05
5      Conor        DWYER      220.66
6       Matt       MCLEAN      222.11
7   Gregorio  PALTRINIERI      222.47
8       Yang          SUN      222.75
9      Peter       BERNEK      223.16

--- Top 10 fastest women's swims ---
        first_name        last_name  final_time
0  McINTOSH Summer  McINTOSH Summer      235.37
1            Katie          LEDECKY      236.81
2            Katie          LEDECKY      237.94
3            Chloe           SUTTON      238.07
4           Jazmin           CARLIN      238.07
5            Katie             HOFF      238.21
6             Hali       FLICKINGER      238.26
7  McINTOSH Summer  McINTOSH Summer      238.28
8            Katie          LEDECKY      238.35
9            Katie          LEDECKY      238.44

--- Average final time by sex ---
  sex  avg_final_time
0   F          256.48
1   M          237.13

--- Average reaction time by sex ---
  sex  avg_reaction_time
0   F              0.742
1   M              0.713

--- Rows missing late splits ---
   missing_late_splits
0                   42

--- Swimmers parsed per race ---
                                                Link  swimmer_count
0  https://www.omegatiming.com/File/00010E0101000...             36
1  https://www.omegatiming.com/File/00010E0101010...             36
2  https://www.omegatiming.com/File/00010E0100000...             32
3  https://www.omegatiming.com/File/00010E0100010...             32
4  https://www.omegatiming.com/File/00010F0209000...             32
5  https://www.omegatiming.com/File/00010F0209010...             32
6  https://www.omegatiming.com/File/0001100001000...             32
7  https://www.omegatiming.com/File/0001100001010...             32
8  https://www.omegatiming.com/File/0001100002000...             32
9  https://www.omegatiming.com/File/0001100002010...             32

--- Fastest swim per race ---
                                                Link  fastest_time
0  https://www.omegatiming.com/File/00010F020D000...        217.78
1  https://www.omegatiming.com/File/00010B00000D0...        220.05
2  https://www.omegatiming.com/File/000113010E010...        222.75
3  https://www.omegatiming.com/File/0001190004010...        223.33
4  https://www.omegatiming.com/File/000113010F010...        223.36
5  https://www.omegatiming.com/File/0001100003000...        223.79
6  https://www.omegatiming.com/File/0001190002010...        223.84
7  https://www.omegatiming.com/File/0001140200010...        224.07
8  https://www.omegatiming.com/File/000111010D000...        224.38
9  https://www.omegatiming.com/File/000111010E000...        224.43

Dataset Summary
Men rows: 1561
Women rows: 1513
Total rows: 3074
Men races: 75
Women races: 75
Total races: 150

In [50]:
import importlib
import ML

importlib.reload(ML)

# Train model
model, mae, importances = ML.train_model(men, women)
print("Model MAE:", mae)

# Prepare data and predict
df_prepared = ML.prepare_data(men, women)
df_results = ML.predict_batch(model, df_prepared)

# Progressive accuracy experiment
prog_df = ML.progressive_accuracy_experiment(men, women)

print("\nPrepared data shape:", df_prepared.shape)
print("Prediction results shape:", df_results.shape)
print("\nPrediction results preview:")
print(df_results.head())

print("\nProgressive accuracy:")
print(prog_df)

SQL database rows: 3074

--- Top 10 fastest men's swims ---
  first_name    last_name  final_time
0      James          GUY      217.78
1      Conor        DWYER      218.10
2     Connor       JAEGER      218.36
3       Zane       GROTHE      219.70
4    Michael        KLUEH      220.05
5      Conor        DWYER      220.66
6       Matt       MCLEAN      222.11
7   Gregorio  PALTRINIERI      222.47
8       Yang          SUN      222.75
9      Peter       BERNEK      223.16

--- Top 10 fastest women's swims ---
        first_name        last_name  final_time
0  McINTOSH Summer  McINTOSH Summer      235.37
1            Katie          LEDECKY      236.81
2            Katie          LEDECKY      237.94
3            Chloe           SUTTON      238.07
4           Jazmin           CARLIN      238.07
5            Katie             HOFF      238.21
6             Hali       FLICKINGER      238.26
7  McINTOSH Summer  McINTOSH Summer      238.28
8            Katie          LEDECKY      238.35
9            Katie          LEDECKY      238.44

--- Average final time by sex ---
  sex  avg_final_time
0   F          256.48
1   M          237.13

--- Average reaction time by sex ---
  sex  avg_reaction_time
0   F              0.742
1   M              0.713

--- Rows missing late splits ---
   missing_late_splits
0                   42

--- Swimmers parsed per race ---
                                                Link  swimmer_count
0  https://www.omegatiming.com/File/00010E0101000...             36
1  https://www.omegatiming.com/File/00010E0101010...             36
2  https://www.omegatiming.com/File/00010E0100000...             32
3  https://www.omegatiming.com/File/00010E0100010...             32
4  https://www.omegatiming.com/File/00010F0209000...             32
5  https://www.omegatiming.com/File/00010F0209010...             32
6  https://www.omegatiming.com/File/0001100001000...             32
7  https://www.omegatiming.com/File/0001100001010...             32
8  https://www.omegatiming.com/File/0001100002000...             32
9  https://www.omegatiming.com/File/0001100002010...             32

--- Fastest swim per race ---
                                                Link  fastest_time
0  https://www.omegatiming.com/File/00010F020D000...        217.78
1  https://www.omegatiming.com/File/00010B00000D0...        220.05
2  https://www.omegatiming.com/File/000113010E010...        222.75
3  https://www.omegatiming.com/File/0001190004010...        223.33
4  https://www.omegatiming.com/File/000113010F010...        223.36
5  https://www.omegatiming.com/File/0001100003000...        223.79
6  https://www.omegatiming.com/File/0001190002010...        223.84
7  https://www.omegatiming.com/File/0001140200010...        224.07
8  https://www.omegatiming.com/File/000111010D000...        224.38
9  https://www.omegatiming.com/File/000111010E000...        224.43

Dataset Summary
Men rows: 1561
Women rows: 1513
Total rows: 3074
Men races: 75
Women races: 75
Total races: 150

In [49]:
import importlib
import os
import matplotlib.pyplot as plt
import analysis

importlib.reload(analysis)
os.makedirs("figures", exist_ok=True)

# Optional example prediction
analysis.run_prediction_example(model, ML.predict)

# Print biggest surprises
analysis.print_biggest_surprises(df_results, n=5)

# Plot 1: progressive accuracy
analysis.plot_progressive_accuracy(prog_df)
plt.savefig("figures/progressive_accuracy.png", bbox_inches="tight")
plt.show()

# Plot 2: residual distribution
analysis.plot_residual_distribution(df_results)
plt.savefig("figures/residual_distribution.png", bbox_inches="tight")
plt.show()

# Plot 3: feature importance
analysis.plot_feature_importance(importances)
plt.savefig("figures/feature_importance.png", bbox_inches="tight")
plt.show()

# Plot 4: split correlations
analysis.plot_split_correlations(df_prepared)
plt.savefig("figures/split_correlations.png", bbox_inches="tight")
plt.show()

print("\nSaved figures:")
print(sorted(os.listdir("figures")))

Predicted final time: 226.37s (3:46.37)

Strongest finishers (model underestimated them most):
      last_name first_name  final_time  predicted_time  residual
2988  GUTIERREZ       Luci      267.06        271.2820    4.2220
152      FOWLER      Tyler      245.48        249.2067    3.7267
711     ABRUZZO     Andrew      230.04        233.5051    3.4651
135       KLUEH    Michael      220.05        223.2244    3.1744
1113         LI     Daniel      235.38        238.2270    2.8470

NameError: name 'prog_df' is not defined

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

feature_cols = [
    "reaction_time", "split_50m", "split_100m", "split_150m",
    "split_200m", "split_250m", "split_300m", "split_350m"
]

X = df[feature_cols]
y = df["final_time"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("rf", RandomForestRegressor(n_estimators=200, random_state=42))
])

model.fit(X_train, y_train)
pred = model.predict(X_test)

mae = mean_absolute_error(y_test, pred)
rmse = np.sqrt(mean_squared_error(y_test, pred))
r2 = r2_score(y_test, pred)

print("MAE:", round(mae, 3))
print("RMSE:", round(rmse, 3))
print("R^2:", round(r2, 3))